#!/usr/bin/env python3
"""Extract the pasteable block out of each preview file into embed/.

Each `*.html` in this directory is a *preview* page: a complete standalone
document (with demo scaffolding) so it can be opened in a browser. The part
meant for the website is fenced between `COPY START` and `COPY END` markers.

Pasting a whole preview file into a CMS block drags the scaffolding along with
it — which is exactly the jank this script exists to prevent. It writes the
fenced block, and nothing else, to `embed/<name>.html`, so "select all, paste"
is always the right move for the files in that folder.

Run after editing any preview file:

    python3 web-snippets/build-embeds.py
"""

import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent
OUT = HERE / "embed"

# The marker lines live inside HTML comments; grab everything between the end
# of the COPY START comment and the start of the COPY END comment.
BLOCK = re.compile(
    r"COPY START.*?-->\n(.*?)\n\s*<!--\s*=+\s*\n\s*COPY END",
    re.DOTALL,
)

BANNER = """<!-- ============================================================
     {title}
     Actuarial Notes — paste this whole file into your CMS block
     (Elementor "HTML" widget, WordPress Custom HTML, Webflow embed…).

     Select all, copy, paste. There is nothing else to strip out:
     this file is only the widget. Do not paste the matching
     web-snippets/{source} preview page instead — that
     one carries demo scaffolding that will fight your page layout.

     Generated by web-snippets/build-embeds.py from
     web-snippets/{source} — edit that file, then re-run
     the script. Hand edits here are lost on the next run.
============================================================ -->
"""

TITLES = {
    "rainbow-flip-card.html": "Rainbow foil flip card",
    "mini-quiz.html": "Mini probability quiz",
    "study-guide-radial.html": "Study guide radial",
}


def main() -> int:
    OUT.mkdir(exist_ok=True)
    written = 0
    for name, title in TITLES.items():
        src = HERE / name
        if not src.exists():
            print(f"missing preview file: {name}", file=sys.stderr)
            return 1
        match = BLOCK.search(src.read_text())
        if not match:
            print(f"no COPY START/END block found in {name}", file=sys.stderr)
            return 1
        body = match.group(1).strip("\n")
        (OUT / name).write_text(BANNER.format(title=title, source=name) + body + "\n")
        print(f"embed/{name}  ({len(body.splitlines())} lines)")
        written += 1
    print(f"\n{written} embed file(s) written to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
