---
id: "masii-2018f-q2"
exam: "Exam MAS-II"
topic: "Likelihood Ratio Test"
learning_objective: "Linear Mixed Models"
difficulty: medium
type: multiple-choice
year: 2018
session: Fall
wiki_link:
  - Concepts/Likelihood+Ratio+Test
  - Concepts/Restricted+Maximum+Likelihood
  - Concepts/Fixed+Effects
  - Concepts/Linear+Mixed+Model
answer: "A"
points: 2
verification:
  status: unverified
  confidence: null
  last_checked: null
  last_checked_by: null
  content_hash: sha256:fe75d002cc1e79c6bc2cd69e8f8960a0d953f5244fdcc4544b3040e555ba9efd
  sources: []
  open_findings: 0
  open_critical: 0
  log: .verify/questions/exam-mas-ii/masii-2018f-002.md
---

In the supplemental material, you have been given a case study, "Systolic Blood Pressure Case Study", showing the results of different treatment options and the description of how that study was set up. There are different ways of setting up models to examine the benefits of the different treatment options. You have been asked which of two models structures will give a better fit to the experience.

*The relevant output from the case study is reproduced below. Change in systolic blood pressure is modelled for 1,680 observations, with random intercepts for 21 hospitals and for 210 doctors nested within them; `Mean_F_G_1` is Mean Group #1, which pools the eight treatments into three mean groups, and `Var_F_G_1` is Variance Group #1.*

**Model 4** — all eight treatments as fixed effects, doctors nested within hospitals, variance grouped under Variance Group #1, fitted by maximum likelihood:

```
## Linear mixed-effects model fit by maximum likelihood
##  Data: systolic_g
##        AIC      BIC    logLik
##   9238.455 9303.573 -4607.227
##
## Random effects:
##  Formula: ~1 | Hospital_F
##         (Intercept)
## StdDev:   0.2597347
##
##  Formula: ~1 | Doctor_F %in% Hospital_F
##         (Intercept) Residual
## StdDev:    0.321243 3.882077
##
## Variance function:
##  Structure: Different standard deviations per stratum
##  Formula: ~1 | Var_F_G_1
##  Parameter estimates:
##        0        1
## 1.000000 0.925956
## Fixed effects: change_systolic ~ Treatment_F
##                  Value Std.Error   DF    t-value p-value
## (Intercept)  -6.792998 0.2753713 1463 -24.668501  0.0000
## Treatment_F2  7.504027 0.3797572 1463  19.760066  0.0000
## Treatment_F3  6.781470 0.3797572 1463  17.857385  0.0000
## Treatment_F4  4.521330 0.3797572 1463  11.905844  0.0000
## Treatment_F5  2.399954 0.3659680 1463   6.557824  0.0000
## Treatment_F6  3.360502 0.3659680 1463   9.182503  0.0000
## Treatment_F7  0.822955 0.3659680 1463   2.248707  0.0247
## Treatment_F8 -1.316800 0.3659680 1463  -3.598129  0.0003
```

**Model 12** — the treatments grouped using Mean Group #1 as fixed effects, doctors nested within hospitals, variance grouped under Variance Group #1, fitted by maximum likelihood:

```
## Linear mixed-effects model fit by maximum likelihood
##  Data: systolic_g
##        AIC      BIC   logLik
##   9301.501 9339.486 -4643.75
##
## Random effects:
##  Formula: ~1 | Hospital_F
##         (Intercept)
## StdDev:   0.2552653
##
##  Formula: ~1 | Doctor_F %in% Hospital_F
##         (Intercept) Residual
## StdDev:  0.09628534 3.942655
##
## Variance function:
##  Structure: Different standard deviations per stratum
##  Formula: ~1 | Var_F_G_1
##  Parameter estimates:
##        0        1
## 1.000000 0.943903
## Fixed effects: change_systolic ~ Mean_F_G_1
##                 Value Std.Error   DF    t-value p-value
## (Intercept)  0.349750 0.2005733 1468   1.743753  0.0814
## Mean_F_G_12 -3.756755 0.2448066 1468 -15.345811  0.0000
## Mean_F_G_13 -7.313573 0.2448066 1468 -29.874906  0.0000
```

Model Structure XYZ has:

- Treatment options should be grouped using Mean Group #1 in the fixed effects section of the model
- A random effect of doctors nested within hospitals
- An assumption that the variance by treatment can be grouped under Variance Group #1

Model Structure STW has:

- All eight treatment options in the fixed effects section of the model
- A random effect of doctors nested within hospitals
- An assumption that the variance by treatment can be grouped under Variance Group #1

The null hypothesis is that the Mean Group #1 should be retained to evaluate the effectiveness of treatment options.

Determine the level of significance at which one would reject the null hypothesis using a likelihood ratio test.

- A) Less than .005
- B) At least .005, but less than .01
- C) At least .01, but less than .025
- D) At least .025, but less than .05
- E) Greater than .05

## Explanation

The two structures share the random effects and Variance Group #1 and differ only in their fixed effects. XYZ pools the eight treatments into the three mean groups of Mean Group #1, and STW gives every treatment its own mean. XYZ is nested in STW because it only adds equality constraints on the treatment means.

When the fixed effects differ, the models must be compared on their **maximum likelihood** fits. REML likelihoods are built on residual contrasts that depend on the fixed-effects design, so two REML log-likelihoods with different fixed effects cannot be compared. That makes STW Model 4 and XYZ Model 12.

STW has 8 fixed-effect parameters (the intercept and seven treatment contrasts) and XYZ has 3 (the intercept and two group contrasts). The random-effect and variance parameters are the same in both, so the null hypothesis imposes $8 - 3 = 5$ restrictions:

$$
\begin{align*}
LR &= 2\left[\ell_{\text{STW}} - \ell_{\text{XYZ}}\right] \\
&= 2\left[-4607.227 - (-4643.750)\right] \\
&= 73.046
\end{align*}
$$

The $\chi^2_5$ critical value at the 0.5% level is 16.75. The statistic is far beyond it, with a p-value of about $2 \times 10^{-14}$. Pooling the treatments into Mean Group #1 loses a real amount of fit, so the null hypothesis is rejected even at the smallest level offered. AIC points the same way (9238.5 for STW against 9301.5 for XYZ).

This falls below 0.005, so the answer is **A**.
