---
id: "masii-2019s-q2"
exam: "Exam MAS-II"
topic: "Linear Mixed Model"
learning_objective: "Linear Mixed Models"
difficulty: hard
type: multiple-choice
year: 2019
session: Spring
wiki_link:
  - Concepts/Linear+Mixed+Model
  - Concepts/Covariance+Structure
  - Concepts/Model+Structure
  - Concepts/AIC
answer: "E"
points: 2
---

In the supplemental material, you have been given a case study, "Systolic Blood Pressure Case Study", showing the results of different treatment options and the description of how that study was set up. You have also been asked to evaluate three statements regarding the results of the study.

*The relevant output from the case study is reproduced below.*

**Distribution of the response** (change in systolic over one year, 2,099 patients):

```
##  change_systolic
##  Min.   :-8.3653
##  1st Qu.:-2.6882
##  Median :-1.1343
##  Mean   :-0.7265
##  3rd Qu.: 0.9967
##  Max.   : 9.0491
```

**Box plot of change in systolic by patient age**

![Box plot of change in systolic blood pressure for each patient age from 50 to 71. The medians rise steadily and close to linearly from about -3 at age 50 to about +1 at age 71, and the box heights stay broadly similar across ages](https://raw.githubusercontent.com/ActuarialNotes/Actuarial-Notes-Wiki/main/Media/Attachments/masii-2019s-q02-change-by-age.png)

**Model 1** — main effects of treatment and age, hospital as a random effect, **constant variance**, fitted by REML:

```
##        AIC      BIC    logLik
##   7327.429 7361.313 -3657.715
```

**Model 5** — the same model but with **variance a function of patient age**, fitted by REML:

```
##        AIC      BIC    logLik
##   7328.156 7367.687 -3657.078
##
## Combination of variance functions:
##  Structure: Exponential of variance covariate
##  Formula: ~Age/2
##  Parameter estimates:
##       expon
##  0.00581435
```

I. Using a linear mixed effects model is not appropriate, since the dependent variable is not normally distributed.
II. The age effect should have been modeled with a quadratic term.
III. One should assume that variance in the change in systolic pressure is a function of the age of the patient rather than assuming constant variance.

Determine which of the above statements are true.

- A) I only
- B) II only
- C) III only
- D) I, II and III
- E) The answer is not given by (A), (B), (C), or (D)

## Explanation

**I is false**, on two counts. First, the normality assumption in a linear mixed model applies to the *residuals* and random effects, not to the marginal distribution of the response. Second, the response here looks close to normal anyway: mean $-0.73$ against median $-1.13$, quartiles roughly symmetric about the centre, and the extremes ($-8.37$ and $+9.05$) about equally far out.

**II is false.** The box plot of change in systolic against patient age shows the medians climbing at a steady rate across the whole range from 50 to 71 — a straight line, with no bend, flattening or turning point. A quadratic term would be fitting curvature the data does not show.

**III is false.** This is the comparison Model 5 exists to make, and the constant-variance model wins:

| | Model 1 (constant variance) | Model 5 (variance a function of age) |
|---|---|---|
| AIC | 7327.4 | 7328.2 |
| BIC | 7361.3 | 7367.7 |

Both criteria prefer Model 1. The variance-function parameter is tiny (0.0058), so the extra parameter buys almost no improvement in log-likelihood (from $-3657.72$ to $-3657.08$) and does not pay for itself. The box plot agrees — the boxes are of broadly similar height across ages. (Both models are fitted by REML, which is what makes their information criteria comparable, since the fixed-effect structure is identical.)

None of the three statements is true, which is not one of options (A) through (D), so the answer is **E**.
