---
id: "masii-2018f-q1"
exam: "Exam MAS-II"
topic: "Likelihood Ratio Test"
learning_objective: "Linear Mixed Models"
difficulty: hard
type: multiple-choice
year: 2018
session: Fall
wiki_link:
  - Concepts/Likelihood+Ratio+Test
  - Concepts/Restricted+Maximum+Likelihood
  - Concepts/Covariance+Structure
  - Concepts/Linear+Mixed+Model
answer: "D"
points: 2
verification:
  status: unverified
  confidence: null
  last_checked: null
  last_checked_by: null
  content_hash: sha256:2c5bd7d49421f524addaba1515354e22ecca6cddb0d5e5732d695d7e284d336a
  sources: []
  open_findings: 0
  open_critical: 0
  log: .verify/questions/exam-mas-ii/masii-2018f-001.md
---

In the supplemental material, you have been given a case study, "Systolic Blood Pressure Case Study", showing the results of different treatment options and the description of how that study was set up. There are different ways of setting up models to examine the benefits of the different treatment options. You have been asked which of two model structures will give a better fit to the experience.

*The relevant output from the case study is reproduced below. Change in systolic blood pressure is modelled for 1,680 observations under eight treatment options, with random intercepts for 21 hospitals and for 210 doctors nested within them; `Var_F_G_1` is Variance Group #1, which places the treatments in two variance strata.*

**Model 1** — all eight treatments as fixed effects, doctors nested within hospitals, constant variance, fitted by REML:

```
## Linear mixed-effects model fit by REML
##  Data: systolic_g
##        AIC      BIC    logLik
##   9247.867 9307.507 -4612.934
##
## Random effects:
##  Formula: ~1 | Hospital_F
##         (Intercept)
## StdDev:   0.2653508
##
##  Formula: ~1 | Doctor_F %in% Hospital_F
##         (Intercept) Residual
## StdDev:   0.2876551 3.752395
##
## Fixed effects: change_systolic ~ Treatment_F
```

**Model 3** — the same model with the variance by treatment grouped under Variance Group #1, fitted by REML:

```
## Linear mixed-effects model fit by REML
##  Data: systolic_g
##        AIC      BIC    logLik
##   9245.032 9310.093 -4610.516
##
## Random effects:
##  Formula: ~1 | Hospital_F
##         (Intercept)
## StdDev:   0.2829815
##
##  Formula: ~1 | Doctor_F %in% Hospital_F
##         (Intercept) Residual
## StdDev:   0.3081544  3.89183
##
## Variance function:
##  Structure: Different standard deviations per stratum
##  Formula: ~1 | Var_F_G_1
##  Parameter estimates:
##         0         1
## 1.0000000 0.9257221
## Fixed effects: change_systolic ~ Treatment_F
```

Model Structure XYZ has:

- All eight treatment options in the fixed effects section of the model
- A random effect of doctors nested within hospitals
- An assumption of constant variance across treatment effects

Model Structure STW has:

- All eight treatment options in the fixed effects section of the model
- A random effect of doctors nested within hospitals
- An assumption that the variance by treatment can be grouped under Variance Group #1

The null hypothesis is that variance is constant across all treatment effects.

Determine the level of significance at which one would reject the null hypothesis using a likelihood ratio test.

- A) Less than .005
- B) At least .005, but less than .01
- C) At least .01, but less than .025
- D) At least .025, but less than .05
- E) Greater than .05

## Explanation

The two structures have the same fixed effects and the same random effects and differ only in the variance assumption, so XYZ is Model 1 and STW is Model 3. XYZ is nested in STW: fixing the stratum-1 standard-deviation ratio (0.9257) at 1 gives back constant variance. Because only the covariance structure changes, the REML fits are the right ones to compare.

STW estimates one extra parameter, the ratio for stratum 1 (stratum 0 is the reference, fixed at 1). The likelihood ratio statistic is

$$
\begin{align*}
LR &= 2\left[\ell_{\text{STW}} - \ell_{\text{XYZ}}\right] \\
&= 2\left[-4610.516 - (-4612.934)\right] \\
&= 4.836
\end{align*}
$$

Under the null hypothesis this is $\chi^2$ with 1 degree of freedom. The null value of the ratio (1) sits inside the parameter space rather than on its boundary, so the ordinary $\chi^2_1$ reference applies. Its critical values are 3.841 at the 5% level and 5.024 at the 2.5% level:

$$
3.841 < 4.836 < 5.024
$$

so the p-value is about 0.028. The null hypothesis of constant variance is rejected at the 5% level but not at the 2.5% level. AIC agrees that STW fits better (9245.0 against 9247.9).

This falls in $[0.025, 0.05)$, so the answer is **D**.
