---
id: "masii-2019f-q14"
exam: "Exam MAS-II"
topic: "Linear Mixed Model"
learning_objective: "Linear Mixed Models"
difficulty: medium
type: multiple-choice
year: 2019
session: Fall
wiki_link:
  - Concepts/Linear+Mixed+Model
  - Concepts/Random+Effects
  - Concepts/Best+Linear+Unbiased+Predictor
  - Concepts/Categorical+Predictor
answer: "B"
points: 2
verification:
  status: unverified
  confidence: null
  last_checked: null
  last_checked_by: null
  content_hash: sha256:71593d9daea2b2ec757c2baf5c864edc7dd01e5aa9ca3c3555b31e924adf7975
  sources: []
  open_findings: 0
  log: .verify/questions/exam-mas-ii/masii-2019f-014.md
---

You are conducting an experiment with two levels: packets of pea plant seeds and the pea plant seeds themselves. You are interested in the effect of different types of light on height of the pea plant after four weeks. Below is the final model:

$$
HEIGHT_{ij} = \beta_0 + \beta_1 \ast TREAT1_j + \beta_2 \ast TREAT2_j + \beta_3 TREAT3_j + \beta_4 \ast MASS_{ij} + \beta_5 \ast NUMSEEDS_j + u_j + \varepsilon_{ij}
$$

- TREAT1, TREAT2, and TREAT3 correspond to 3 of the 4 light types used
- MASS is the mass of the given seed in grams
- NUMSEEDS is the number of seeds in the seed packet
- The model output is given below:

```
## Fixed effects: height ~ treatment + mass + numseeds
##
##               Value   Std.Error   DF
## (Intercept)  10.118      0.7067  294
## TREAT1       -5.320      0.3493   22
## TREAT2       -7.824      0.3388   22
## TREAT3       -4.373      0.3474   22
## mass          0.111      0.1049  294
## numseeds     -0.053      0.0422   22
```

Determine the equation to predict pea plant height for a specific seed in a specific seed packet under TREAT1.

- A) $\widehat{HEIGHT}_{ij} = 4.798 + 0.111 \ast MASS_{ij} - 0.053 \ast NUMSEEDS_j + \hat{u}_j + \varepsilon_{ij}$
- B) $\widehat{HEIGHT}_{ij} = 4.798 + 0.111 \ast MASS_{ij} - 0.053 \ast NUMSEEDS_j + \hat{u}_j$
- C) $\widehat{HEIGHT}_{ij} = 4.798 + 0.111 \ast MASS_{ij} - 0.053 \ast NUMSEEDS_j$
- D) $\widehat{HEIGHT}_{ij} = 10.118 + 0.111 \ast MASS_{ij} - 0.053 \ast NUMSEEDS_j + \hat{u}_j + \varepsilon_{ij}$
- E) $\widehat{HEIGHT}_{ij} = 10.118 + 0.111 \ast MASS_{ij} - 0.053 \ast NUMSEEDS_j + \hat{u}_j$

## Explanation

Three decisions build the right equation.

**The intercept.** Under TREAT1 the indicator $TREAT1_j = 1$ while $TREAT2_j = TREAT3_j = 0$, so the treatment coefficient folds into the intercept:

$$
\begin{align*}
10.118 + (-5.320) &= 4.798
\end{align*}
$$

This eliminates (D) and (E), which leave the reference-treatment intercept in place.

**The random effect stays.** The prediction is for a *specific seed packet*, so it is a conditional (subject-specific) prediction and must include that packet's predicted random effect $\hat{u}_j$. This eliminates (C), which gives the population-average prediction instead.

**The residual goes.** $\varepsilon_{ij}$ has mean zero and is not observable, so it never appears in a fitted prediction — including it would be predicting the noise. This eliminates (A).

The answer is **B**.
