---
id: "masii-2019s-q1"
exam: "Exam MAS-II"
topic: "Linear Mixed Model"
learning_objective: "Linear Mixed Models"
difficulty: hard
type: multiple-choice
year: 2019
session: Spring
wiki_link:
  - Concepts/Linear+Mixed+Model
  - Concepts/Interaction
  - Concepts/Fixed+Effects
  - Concepts/Hypothesis+Testing
answer: "B"
points: 2
verification:
  status: unverified
  confidence: null
  last_checked: null
  last_checked_by: null
  content_hash: sha256:d60ab807b6943923f0551f4fa8f57319a9a349df197305b9a02c17bc46e30c24
  sources: []
  open_findings: 0
  log: .verify/questions/exam-mas-ii/masii-2019s-001.md
---

In the supplemental material, you have been given a case study, "Systolic Blood Pressure Case Study", showing the results of different treatment options and the description of how that study was set up. You have also been asked to evaluate three statements regarding the results of the study.

*The relevant output from the case study is reproduced below. Change in systolic blood pressure is measured over one year for 2,099 patients across 21 hospitals; hospital enters as a random effect and the three treatments are coded 0 (reference), 1 and 2.*

**Box plot of change in systolic by treatment**

![Box plot of change in systolic blood pressure by treatment. Treatments 0 and 1 both sit below zero, with medians near -2 and -1.5, while treatment 2 sits entirely above zero with a median near 3](https://raw.githubusercontent.com/ActuarialNotes/Actuarial-Notes-Wiki/main/Media/Attachments/masii-2019s-q01-change-by-treatment.png)

**Model 1** — main effects of treatment and age, hospital as a random effect, constant variance:

```
## Linear mixed-effects model fit by REML
##   Data: systolic_g
##        AIC      BIC    logLik
##   7327.429 7361.313 -3657.715
##
## Random effects:
##  Formula: ~1 | hospital
##         (Intercept) Residual
## StdDev:   0.4262212 1.361067
##
## Fixed effects: change_systolic ~ Treatment + Age
##                  Value Std.Error   DF   t-value p-value
## (Intercept) -12.487130 0.3181821 2075 -39.24523       0
## Treatment1    0.654929 0.0709604 2075   9.22950       0
## Treatment2    5.024052 0.0784480 2075  64.04309       0
## Age           0.165733 0.0049154 2075  33.71726       0
##
##             numDF denDF   F-value p-value
## (Intercept)     1  2075   55.3061  <.0001
## Treatment       2  2075 2521.6816  <.0001
## Age             1  2075 1136.8534  <.0001
```

**Model 3** — same main effects plus a treatment-by-age interaction:

```
## Fixed effects: change_systolic ~ Treatment + Age + Treatment * Age
##                     Value Std.Error   DF    t-value p-value
## (Intercept)    -12.383800 0.5482496 2073 -22.587888  0.0000
## Treatment1       0.638400 0.7128276 2073   0.895588  0.3706
## Treatment2       4.672223 0.7881578 2073   5.928030  0.0000
## Age              0.164038 0.0088235 2073  18.591054  0.0000
## Treatment1:Age   0.000267 0.0116514 2073   0.022920  0.9817
## Treatment2:Age   0.005757 0.0128419 2073   0.448268  0.6540
##
##               numDF denDF   F-value p-value
## (Intercept)       1  2073   55.3245  <.0001
## Treatment         2  2073 2519.5614  <.0001
## Age               1  2073 1135.9036  <.0001
## Treatment:Age     2  2073    0.1305  0.8777
```

I. None of the treatments significantly reduce systolic blood pressure.
II. The age of the patient has a significant effect on the change in blood pressure expected over a one-year time period.
III. The age of the patient interacts significantly with the treatment.

Determine which of the above statements are true.

- A) I only
- B) II only
- C) III only
- D) I, II and III
- E) The answer is not given by (A), (B), (C), or (D)

## Explanation

**I is false.** Treatment is overwhelmingly significant ($F = 2521.7$, $p < 0.0001$), and the box plot shows that treatments 0 and 1 both sit clearly below zero — change in systolic is negative, meaning blood pressure falls. Reading the same thing off Model 1 at the mean age of about 61:

$$
\begin{align*}
\text{Treatment 0:} \quad -12.487 + 0.1657(61) &= -2.38 \\
\text{Treatment 1:} \quad -12.487 + 0.655 + 0.1657(61) &= -1.72
\end{align*}
$$

Both reduce systolic blood pressure, so it is not true that *none* of the treatments do. (Treatment 2 raises it, at $+2.65$.)

**II is true.** Age carries $t = 33.7$ with $p \approx 0$ in Model 1 and $F = 1136.9$ with $p < 0.0001$. Each additional year of age adds about 0.166 to the expected change — comfortably significant.

**III is false.** This is what Model 3 is for. Neither interaction coefficient is close to significant ($p = 0.9817$ and $p = 0.6540$), and the joint F-test on the interaction is $F = 0.1305$ with $p = 0.8777$. Adding the interaction also *worsens* AIC (7345.4 against Model 1's 7327.4). The treatment effect does not vary with age.

Only statement II, so the answer is **B**.
