---
id: "masii-2019f-q1"
exam: "Exam MAS-II"
topic: "Linear Mixed Model"
learning_objective: "Linear Mixed Models"
difficulty: medium
type: multiple-choice
year: 2019
session: Fall
wiki_link:
  - Concepts/Linear+Mixed+Model
  - Concepts/Random+Effects
  - Concepts/Covariance+Structure
  - Concepts/AIC
answer: "B"
points: 2
verification:
  status: unverified
  confidence: null
  last_checked: null
  last_checked_by: null
  content_hash: sha256:f84056dbc74a64cfbe7301e28be3fa0abc3c96fddb5cb804d59fa235974217ba
  sources: []
  open_findings: 0
  open_critical: 0
  log: .verify/questions/exam-mas-ii/masii-2019f-001.md
---

In the supplemental material, you have been given a case study, "Warranty Payments Case Study". You have also been asked to evaluate three statements regarding the results of the study.

*The relevant output from the case study is reproduced below. The log of individual warranty payments for one product is modelled with linear mixed-effects models in R's `nlme` package, using payment lag (months since sale, 1 to 12) and month of sale as fixed effects.*

**Study set-up**, as the case study describes it:

> The product is sold in 100 different stores, but only three stores are included in the sample. Those three stores are under the variable Store and are denoted by: Store_1, Store_2 and Store_3.

**Model I** — payment lag as a fixed effect, store as a random effect, constant variance:

```
## Linear mixed-effects model fit by REML
##  Data: Repair
##        AIC      BIC   logLik
##   191545.6 191580.3 -95768.8
##
## Random effects:
##  Formula: ~1 | Store
##         (Intercept) Residual
## StdDev:   0.2302979 2.220299
##
## Fixed effects: Log_Payment ~ Pay_Lag
##                 Value  Std.Error    DF  t-value p-value
## (Intercept) 0.6518274 0.13489914 43196  4.83196       0
## Pay_Lag     0.2986713 0.00309451 43196 96.51643       0
```

**Model III** — payment lag and month sold as fixed effects, store as a random effect, variance a function of payment lag using the exponential variance function:

```
wgt_function_1 <- varExp(form = ~Pay_Lag/2)

Model_III <- lme (Log_Payment ~  Pay_Lag + Sale_Month, data =Repair,
                random = ~1|Store,
                weights=wgt_function_1)
summary(Model_III)
## Linear mixed-effects model fit by REML
##  Data: Repair
##        AIC      BIC    logLik
##   181627.8 181766.6 -90797.89
##
## Random effects:
##  Formula: ~1 | Store
##         (Intercept) Residual
## StdDev:  0.02249708 1.012199
##
## Variance function:
##  Structure: Exponential of variance covariate
##  Formula: ~Pay_Lag/2
##  Parameter estimates:
##     expon
## 0.2061607
## Fixed effects: Log_Payment ~ Pay_Lag + Sale_Month
```

**Model IV** — the same fixed and random effects, with variance a function of payment lag using the power transform of payment time:

```
wgt_function_3 <- varPower(form =~Pay_Lag)

Model_IV <- lme (Log_Payment ~  Pay_Lag + Sale_Month, data =Repair,
                random = ~1|Store,
                weights=wgt_function_3)
summary(Model_IV)
## Linear mixed-effects model fit by REML
##  Data: Repair
##        AIC      BIC    logLik
##   181693.1 181831.8 -90830.53
##
## Random effects:
##  Formula: ~1 | Store
##         (Intercept)  Residual
## StdDev:  0.01945993 0.8774883
##
## Variance function:
##  Structure: Power of variance covariate
##  Formula: ~Pay_Lag
##  Parameter estimates:
##     power
## 0.4884623
## Fixed effects: Log_Payment ~ Pay_Lag + Sale_Month
```

- I. Model I is a marginal model.
- II. Placing the Store variable in the random effects category is appropriate since we only have a subset of possible results.
- III. Model III is a nested model of Model IV.

Determine which of the above statements are true.

- A) I only
- B) II only
- C) III only
- D) I, II and III
- E) The answer is not given by (A), (B), (C), or (D)

## Explanation

**I is false.** A marginal model has no random effects. It specifies the covariance of the observations directly through the residual covariance matrix, $\mathbf{V}_i = \mathbf{R}_i$. Model I contains a random intercept for each store (`Random effects: Formula: ~1 | Store`, with standard deviation 0.230), so it is a linear mixed model. It *implies* a marginal covariance $\mathbf{Z}_i\mathbf{D}\mathbf{Z}_i^\top + \mathbf{R}_i$, but that does not make it a marginal model.

**II is true.** A factor belongs in the random effects when its observed levels are a sample from a larger population of levels and the conclusions are meant for that whole population. The product is sold in 100 stores and only three of them are in the data, so Store is the textbook random factor. Its effect is described by a single variance (a standard deviation of 0.230 in Model I) instead of a separate fixed coefficient for each sampled store.

**III is false.** Models III and IV have identical fixed effects (`Log_Payment ~ Pay_Lag + Sale_Month`) and identical random effects, and differ only in the variance function:

$$
\begin{align*}
\text{Model III (exponential):} \quad \mathrm{Var}(\varepsilon_{ij}) &= \sigma^2 e^{2\delta v_{ij}} \\
\text{Model IV (power):} \quad \mathrm{Var}(\varepsilon_{ij}) &= \sigma^2 \lvert v_{ij} \rvert^{2\delta}
\end{align*}
$$

Both reduce to constant variance at $\delta = 0$, but no value of the exponential parameter reproduces the power function, and no value of the power parameter reproduces the exponential. Each model also has the same number of parameters. Recovering it from $\text{AIC} = -2\ell + 2k$:

$$
\begin{align*}
\text{Model III:} \quad 2k &= 181627.8 + 2(-90797.89) \\
                           &= 32.02 \\
\text{Model IV:} \quad 2k &= 181693.1 + 2(-90830.53) \\
                          &= 32.04
\end{align*}
$$

That gives $k = 16$ for both. A nested model must be a restricted version of the larger model, with fewer free parameters, so neither model is nested in the other. They are compared with an information criterion (Model III has the lower AIC, 181627.8 against 181693.1), not with a likelihood ratio test.

Only statement II is true, so the answer is **B**.
