#!/usr/bin/env python3
"""
generate_validation_status.py — write `Validation Status.md`, the vault-level
dashboard of what VERIFY has and has not checked.

Generated, like `Concepts Without Review Questions.md`: edit this script, not the
page. Run it after a sweep, or from the weekly workflow.

The page is deliberately blunt about the denominator. A dashboard that only
counts what has been verified flatters the project; one that leads with the
percentage still unchecked tells a maintainer where the next sweep should go, and
tells a reader how much of what they are studying has actually been checked
against a source. That honesty is the whole product here.

Usage:
  python3 scripts/generate_validation_status.py
  python3 scripts/generate_validation_status.py --check   # non-zero if stale
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import verify_lib as V  # noqa: E402

REPORT = V.REPO_ROOT / "Validation Status.md"

STATUS_ORDER = ["verified", "in_review", "disputed", "stale", "unverified"]
STATUS_LABELS = {
    "verified": "Verified",
    "in_review": "Under review",
    "disputed": "Disputed",
    "stale": "Stale (content changed)",
    "unverified": "Unverified",
}


def area_for(rel: str) -> str:
    if rel.startswith("questions/"):
        parts = rel.split("/")
        return f"Questions — {parts[1]}" if len(parts) > 2 else "Questions"
    if rel.startswith("Concepts/"):
        return "Concepts"
    if rel.startswith("Resources/"):
        parts = rel.split("/")
        return f"Resources — {parts[1]}" if len(parts) > 2 else "Resources"
    return "Exam pages"


def pct(part: int, whole: int) -> str:
    return f"{(100 * part / whole):.1f}%" if whole else "—"


def build() -> str:
    by_area: dict[str, Counter] = defaultdict(Counter)
    totals: Counter = Counter()
    open_by_severity: Counter = Counter()
    flagged: list[tuple[str, int, str]] = []      # critical findings
    disputed: list[str] = []
    stale: list[str] = []
    recently_verified: list[tuple[str, str, int]] = []

    files = list(V.iter_content_files())
    for path in files:
        rel = V.rel_path(path)
        try:
            block = V.parse_verification(path.read_text(encoding="utf-8")) or {}
        except ValueError:
            block = {"status": "malformed"}
        status = str(block.get("status") or "unverified")
        area = area_for(rel)
        by_area[area][status] += 1
        totals[status] += 1

        critical = block.get("open_critical") or 0
        if isinstance(critical, int) and critical > 0:
            flagged.append((rel, critical, str(block.get("log") or "")))
        if status == "disputed":
            disputed.append(rel)
        if status == "stale":
            stale.append(rel)
        if status == "verified":
            recently_verified.append((
                rel,
                str(block.get("last_checked") or ""),
                len(block.get("sources") or []),
            ))

        log = V.read_log(rel)
        if log:
            for finding in log.open_findings():
                open_by_severity[finding.severity or "unclassified"] += 1

    total = len(files)
    checked = totals["verified"]

    lines: list[str] = [
        "# Validation Status",
        "",
        f"> Generated {date.today().isoformat()}. **{checked} of {total} content files "
        f"({pct(checked, total)})** have been verified against a citable source.",
        "",
        "This page is generated by `scripts/generate_validation_status.py` — edit the script, "
        "not the page. What the statuses mean, and what it takes to earn each one, is in "
        "[[docs/verification|docs/verification.md]].",
        "",
        "## Summary",
        "",
        "| Status | Files | Share |",
        "|---|---:|---:|",
    ]
    for status in STATUS_ORDER:
        lines.append(f"| {STATUS_LABELS[status]} | {totals[status]} | {pct(totals[status], total)} |")
    lines.append(f"| **Total** | **{total}** | |")
    lines += ["", "## By area", "", "| Area | Verified | Under review | Disputed | Stale | Unverified | Total |",
              "|---|---:|---:|---:|---:|---:|---:|"]
    for area in sorted(by_area):
        counts = by_area[area]
        area_total = sum(counts.values())
        lines.append(
            f"| {area} | {counts['verified']} | {counts['in_review']} | {counts['disputed']} "
            f"| {counts['stale']} | {counts['unverified']} | {area_total} |"
        )

    lines += ["", "## Open findings", ""]
    if not open_by_severity:
        lines.append("No open findings on record.")
    else:
        lines += ["| Severity | Open |", "|---|---:|"]
        for severity in ("critical", "major", "minor", "nit", "unclassified"):
            if open_by_severity[severity]:
                lines.append(f"| {severity} | {open_by_severity[severity]} |")

    lines += ["", "### Needs attention first", ""]
    if flagged:
        lines.append(
            "Pages carrying an **unresolved critical finding**. Questions here are kept out of "
            "quiz sessions until the finding is closed."
        )
        lines.append("")
        for rel, count, log in sorted(flagged):
            lines.append(f"- `{rel}` — {count} critical · log: `{log}`")
    else:
        lines.append("No unresolved critical findings. ")

    if disputed:
        lines += ["", "### Disputed", "",
                  "Sources conflict, or a critical finding is unresolved. A human has to settle these.", ""]
        lines += [f"- `{rel}`" for rel in sorted(disputed)]

    if stale:
        lines += ["", "### Stale", "",
                  "Verified once, then edited. The check no longer speaks for what is on the page.", ""]
        lines += [f"- `{rel}`" for rel in sorted(stale)]

    if recently_verified:
        lines += ["", "## Recently verified", "", "| Page | Checked | Sources |", "|---|---|---:|"]
        for rel, checked_on, source_count in sorted(
            recently_verified, key=lambda row: row[1], reverse=True
        )[:25]:
            lines.append(f"| `{rel}` | {checked_on or '—'} | {source_count} |")

    lines += [
        "",
        "---",
        "",
        "Something here look wrong? Every page in the app carries a validation badge — tap it "
        "to read that page's log or report an error. Reports are appended to the log and read "
        "in full by the next validation pass.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit non-zero if the page is out of date")
    args = ap.parse_args()

    content = build()
    if args.check:
        current = REPORT.read_text(encoding="utf-8") if REPORT.is_file() else ""
        # The generated-on line changes every day; compare everything else.
        strip = lambda text: "\n".join(  # noqa: E731
            ln for ln in text.split("\n") if not ln.startswith("> Generated ")
        )
        if strip(current) != strip(content):
            print(f"{REPORT.name} is out of date — run scripts/generate_validation_status.py")
            return 1
        print(f"{REPORT.name} is up to date")
        return 0

    REPORT.write_text(content, encoding="utf-8")
    print(f"Wrote {REPORT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
